### ISSUE TITLE
Cannot register assemblies

### ISSUE THREAD

**Issue by Expecho** [Microsoft/AzureDatalakeToolsForVSCode#3]
I have successfully connected Visual Studio Code to my ADL account, and when I issue the command `adl: list accounts` it is listened as well. 

When opening the folder I see I my u-sql file is connected to that account (the account is listened in the right bottom corner)

However, when I try to register an assembly using `adl: register assembly` I cannot pick any account. It says "There are no entries to pick from".

What am I doing wrong here?

This is the content of the configuration file:

    {
        "scripts": [
            {
                "path": "adl_settings.json",
                "account": "xxx"
            },
            {
                "path": "query.usql",
                "account": "xxx",
                "optionalSettings": {
                    "runtimeVersion": "",
                    "priority": "",
                    "degreeOfParallelism": "",
                    "jobInformationOutputPath": ""
                }
            }
        ]
    }

**Comment by mandywAtGitHub** [comment]
Hi Expecho,
Sorry for the inconvenience. It seems like a bug. We will release a new update with refined register assemblies in early July.  
If it blocked you work. You can try this private vsix by command 'Extensions: Install from vsix'
https://github.com/Microsoft/AzureDatalakeToolsForVSCode/blob/master/usql-vscode-ext-0.2.3-Dogfood.vsix

Since it is dogfood version, so there might be minor bugs.

**Comment by mandywAtGitHub** [comment]
Hi Expecho,
We have already pushed the July release. Please update your version. Thanks a lot for your feedback!
